In [24]:
import tensorflow as tf

### **Tensors**

"A tensor is a generalization of vectors and matrices to potentially higher dimensions, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)

Tensors are a fundamental aspect of TensorFlow. They are the main objects that are passed and manipulated throughout each program. Each tensor represents a partially defined computation that will eventually produce a value. TensorFlow programs work by building a  graph of Tensor Objects that detail how tensors are related. Running different parts of the graph allow result to be generated.

In easy words **It is a vector generalized to higher dimensions**

# Each Tensor has a data type and shape.

**Data Types include :** float32, int32, string and others.

**Shape :** represents the dimension of data.

**Vector :** It is a datapoint. and the reason we call it a vector is because it doesn't necessarily have a coordinate like 2D data points.
A vector can have any amount of dimensions.

n-dimension vector has n numbers.

### **Creating Tensors**

Below is an example of how to create some different tensors.

In [25]:
string = tf.Variable("this is a string", tf.string) # this is 0D since it only has a single value
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)
# All these have shape 1, rank/degree 0 also called scalar & have just one value

### **Rank/Degree of Tensors**

Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a tensor of rank 0, also known as a scalar

Now we'll create some tensors of higher degrees/ranks.


In [26]:
rank1_tensor = tf.Variable(["Test","ok"], tf.string) # this is 1D bcz it has a list and it can have n number pf elements inside
rank2_tensor = tf.Variable([["test","ok","why"],["test","yes","not"]], tf.string) # this is 2d bcz it has a list inside a list, this is typically called matrix
# also note matrices must be square that means if we have mutiple dimensions, then all dimensions will have same number of elements

#therefore the deepest level of a nested list is equal to its rank in python & R

**To determine the rank** of a tensor we call the following

In [27]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### **Shape of Tensors**

Shape is simply the amount of elements that exist in each dimension. TensorFlow will try to determine the shape of a tensor but sometimes it may be unknown.
To **get the shape** of a tensor we use the shape attribute

In [28]:
rank2_tensor.shape   # shape tells us how many items do we have in each dimension
# here 2,3 means that we have 2 lists with 3 elements each
# if we had 1D array we would have got just one thing, the number of elements
# for 0D we would have got empty brackets

TensorShape([2, 3])

### **Changing Shape**

number of elements in a tensor is the product of the sizes of all its shapes. These are often many shapes that have same number of elements, making it convinient to change the shape of the tensor as shown below

In [29]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
# this will generate a tensor with 1 interior list, each of which that contains 2 lists, each with 3 elements(1s)

tensor2 = tf.reshape(tensor1,[2,3,1]) # reshape existing data to the shape [2,3,1]
tensor3 = tf.reshape(tensor2,[3,-1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                      # this will reshape the tensor to [3,2] bcz there are six elements and 6=3*2

# The number of elements in the reshaped tensor MUST match the number in the original
# which means 1*2*3=2*3*1=3*2=6 elements here

Lets look at our tensors now

In [30]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### **Types of Tensor**

- Variable
- Constant
- Placeholder
- SparseTensor

With exception of `variable`, all of these tensors are **immutable**, meaning their value may not change during execution.

For now it is sufficient to know that we use variable tensor when we want to change the value of our tensor. (all the tensors we have created were variable)

If we are using a constant tensor we can not change it, however we can copy it.

Note : their are a few other thensors as well

### **Evaluating Tensors**

There are times where we need to evaluate a tensor, or in other words get its value. Since Tensors represent a partially completed computatation we sometimes need to run what's called a session to evaluate the tensor.

There are many different ways to achieve this but the simplest way is given below

In [ ]:
with tf.Session() as sess: # creates a session using the default graph
  tensor.eval()            # tensor is the name of your tensor

In the code we evaluate the tensor variable that was stored in the **default graph**. The default graph holds all operations not specified to any other graph. It is possible to create our own seperate graphs but for now we will stick with default.

### **Sources**

Most of the information is directly taken from tensorflow website :

https://www.tensorflow.org/guide/tensor

In [39]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

t = tf.zeros([5,5,5,5])
print(t)

#reshaping
t = tf.reshape(t, [625])
print(t)

t = tf.reshape(t, [125,-1])
print(t)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>
tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0